sudo: required
services:
  - docker



before_install:
  - docker build -t ruch9211/docker-react -f Dockerfile.dev .

script:
  - docker run ruch9211/docker-react npm run test  -- --coverage  
  #- docker -e CI=true run ruch9211/docker-react npm run test
